version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bugtracker
      POSTGRES_USER: buguser
      POSTGRES_PASSWORD: bugpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: daphne bug_tracker.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://buguser:bugpassword@db:5432/bugtracker

volumes:
  postgres_data:
